#!/usr/bin/env python
"""
 Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Permission is hereby granted, free of charge, to any person obtaining a copy of this
 software and associated documentation files (the "Software"), to deal in the Software
 without restriction, including without limitation the rights to use, copy, modify,
 merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

import sys
import random

import rospy
from geometry_msgs.msg import Twist

class Mover():
    def __init__(self, num_robots):
        self._cmd_pubs = list()
        for i in range(num_robots):
            self._cmd_pubs.append(rospy.Publisher('/model/turtlebot3_waffle_pi_%d/cmd_vel' % (i+1), Twist, queue_size=1))

    def move_random(self):
        self.twist = Twist()

        r = rospy.Rate(1)
        while not rospy.is_shutdown():
            i = 1
            for cmd_pub in self._cmd_pubs:
                direction = random.uniform(-10.0, 10.0)
                angular_speed = random.uniform(-10.0, 10.0)
                self.twist.angular.z = angular_speed
                self.twist.linear.x = direction
                cmd_pub.publish(self.twist)
                rospy.loginfo("Moving Robot #%d:\n%s", i, self.twist)
                i += 1
            r.sleep()

def main():
    rospy.init_node('move_random')

    num_robots = 1
    my_argv = rospy.myargv(argv=sys.argv)
    if (len(my_argv) >= 2):
        num_robots = int(my_argv[1])
    rospy.loginfo('Moving %d Robots', num_robots);
    try:
        rotator = Mover(num_robots)
        rotator.move_random()
    except rospy.ROSInterruptException:
        pass

if __name__ == '__main__':
    main()
