name: "Lint rosbag-uploader-ros1"
on:
  pull_request:

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-bionic-ros-eloquent-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, flake8, pep257, xmllint]
    steps:
      - run: sudo chown -R rosbuild:rosbuild "$HOME" .
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: dashing
          linter: ${{ matrix.linter }}
          package-name: |
            aws_robomaker_simulation_common
            cloudwatch_simulation
            cloudwatch_robot
