name: build-and-bundle
on: 
  pull_request:
  push:
    branches:
      - ros1
  schedule:
    - cron: '0 14 * * *'  # run at 2 pm everyday

jobs:
  build_and_bundle_ros1:
    strategy:
      matrix:
        distro: ['kinetic', 'melodic']
        gazebo: [7, 9]
        include:
        - distro: kinetic
          gazebo: 7
          ubuntu_distro: xenial
        - distro: kinetic
          gazebo: 9
          ubuntu_distro: xenial
        - distro: melodic
          gazebo: 9
          ubuntu_distro: bionic
        exclude:
        - distro: 'melodic'
          gazebo: 7
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.ref != 'refs/heads/ros2'
    name: 'Build and Bundle (ROS1)'
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distro }}-ros-${{ matrix.distro }}-ros-base-latest
    outputs:
      robot_ws_build_result: ${{ steps.robot_ws_build.outcome }}
      simulation_ws_build_result: ${{ steps.simulation_ws_build.outcome }}
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v1
    - name: Setup Permissions
      run: |
        # TODO(ros-tooling/setup-ros-docker#7): calling chown is necessary for now
        sudo chown -R rosbuild:rosbuild "$HOME" .
    - id: robot_ws_build
      name: Build and Bundle Robot Workspace
      uses: aws-robotics/aws-robomaker-github-actions/robomaker-sample-app-ci@2.1.1
      with:
        ros-distro: ${{ matrix.distro }}
        gazebo-version: ${{ matrix.gazebo }}
        workspace-dir: robot_ws
        generate-sources: true
    - id: simulation_ws_build
      name: Build and Bundle Simulation Workspace
      uses: aws-robotics/aws-robomaker-github-actions/robomaker-sample-app-ci@2.1.1
      with:
        ros-distro: ${{ matrix.distro }}
        gazebo-version: ${{ matrix.gazebo }}
        workspace-dir: simulation_ws

  log_workflow_status_to_cloudwatch:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    needs:
    - build_and_bundle_ros1
    if: ${{ always() && github.event_name != 'pull_request' }}
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ROS1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROS1 }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Log Robot Workspace Build Status
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        namespace: RobotWorkspaceBuild
        metric-value: ${{ ! contains(needs.build_and_bundle_ros1.outputs.robot_ws_build_result, 'failure') }}
    - name: Log Simulation Workspace Build Status
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        namespace: SimulationWorkspaceBuild
        metric-value: ${{ ! contains(needs.build_and_bundle_ros1.outputs.simulation_ws_build_result, 'failure') }}
